test:	dan pept

dan:
	../bin/rism3d -w tip3p-dr056-np2048.rbin dan.rtxt

pept:
	../bin/rism3d -w tip3p-dr056-np2048.rbin pept.rtxt

.PHONY: clean
clean:
	rm dan_cuv.rbin dan_huv.rbin
	rm pept_cuv.rbin pept_huv.rbin
